### ISSUE TITLE
hang after returning certificate

### ISSUE THREAD

**Issue by guymguym** [vmolsa/webrtc-native#3]
```
$ node test
WebRtc VoiceEngine codecs:
ISAC/16000/1 (103)
ISAC/32000/1 (104)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: ISAC/48000/1 (105)
PCMU/8000/1 (0)
PCMA/8000/1 (8)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: PCMU/8000/2 (110)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: PCMA/8000/2 (118)
ILBC/8000/1 (102)
G722/8000/1 (9)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: G722/8000/2 (119)
opus/48000/2 (111)
CN/8000/1 (13)
CN/16000/1 (105)
CN/32000/1 (106)
telephone-event/8000/1 (126)
red/8000/1 (127)
WebRtcVideoEngine2::WebRtcVideoEngine2()
WebRtcVoiceEngine::Init
webrtc: CheckPlatform
webrtc: current platform is MAC
webrtc: CreatePlatformSpecificObjects
webrtc: output: kPlatformDefaultAudio
webrtc: Mac OS X Audio APIs will be utilized
webrtc: AttachAudioBuffer
webrtc:   OS info: OS X
webrtc:  Hardware model: MacBookAir6,2
webrtc:   number of availiable waveform-audio output devices is 3
webrtc:  Output device: Apple Inc. Built-in Output
webrtc: AudioMixerManagerMac::OpenSpeaker(id=38)
webrtc:  No process has hogged the input device
webrtc:   number of availiable waveform-audio input devices is 2
webrtc:  Input device: Apple Inc. Built-in Microphone
webrtc: AudioMixerManagerMac::OpenMicrophone(id=48)
webrtc:  No process has hogged the input device
webrtc: output: available=1
webrtc: output: available=1
webrtc: TransmitMixer::SetAudioProcessingModule(audioProcessingModule=0x150aff0)
webrtc: OutputMixer::SetAudioProcessingModule(audioProcessingModule=0x150aff0)
WebRtc VoiceEngine Version:
VoiceEngine 4.1.0
Applying audio options: AudioOptions {aec: true, agc: true, ns: true, hf: true, swap: false, typing: true, conference: false, agc_delta: 0, experimental_agc: false, experimental_aec: false, delay_agnostic_aec: false, experimental_ns: false, aec_dump: false, }
Error(webrtcvoiceengine.cc:1446): webrtc: Built-in AEC not supported on this platform
High pass filter enabled? 1
Stereo swapping enabled? 0
Typing detection is enabled? 1
Adjust agc delta is 0
Adjusting AGC level from default -2dB to -2dB
Aec dump is enabled? 0
Delay agnostic aec is enabled? 0
Experimental aec is enabled? 0
Experimental ns is enabled? 0
WebRtc VoiceEngine codecs:
opus/48000/2 (111)
ISAC/16000/1 (103)
ISAC/32000/1 (104)
G722/8000/1 (9)
ILBC/8000/1 (102)
PCMU/8000/1 (0)
PCMA/8000/1 (8)
CN/32000/1 (106)
CN/16000/1 (105)
CN/8000/1 (13)
red/8000/1 (127)
telephone-event/8000/1 (126)
WebRtcVoiceEngine::Init Done!
WebRtcVideoEngine2::Init
Applying audio options: AudioOptions {aec: true, agc: true, ns: true, hf: true, swap: false, typing: true, conference: false, agc_delta: 0, experimental_agc: false, experimental_aec: false, delay_agnostic_aec: false, experimental_ns: false, aec_dump: false, }
Error(webrtcvoiceengine.cc:1446): webrtc: Built-in AEC not supported on this platform
High pass filter enabled? 1
Stereo swapping enabled? 0
Typing detection is enabled? 1
Adjust agc delta is 0
Adjusting AGC level from default -2dB to -2dB
Aec dump is enabled? 0
Delay agnostic aec is enabled? 0
Experimental aec is enabled? 0
Experimental ns is enabled? 0
Setting microphone to (id=0, name=Default device) and speaker to (id=0, name=Default device)
Set microphone to (id=0 name=Default device) and speaker to (id=0 name=Default device)
Making key pair
WebRtc VoiceEngine codecs:
ISAC/16000/1 (103)
ISAC/32000/1 (104)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: ISAC/48000/1 (105)
PCMU/8000/1 (0)
PCMA/8000/1 (8)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: PCMU/8000/2 (110)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: PCMA/8000/2 (118)
ILBC/8000/1 (102)
G722/8000/1 (9)
Warning(webrtcvoiceengine.cc:569): Unexpected codec: G722/8000/2 (119)
opus/48000/2 (111)
CN/8000/1 (13)
CN/16000/1 (105)
CN/32000/1 (106)
telephone-event/8000/1 (126)
red/8000/1 (127)
WebRtcVideoEngine2::WebRtcVideoEngine2()
WebRtcVoiceEngine::Init
webrtc: CheckPlatform
webrtc: current platform is MAC
webrtc: CreatePlatformSpecificObjects
webrtc: output: kPlatformDefaultAudio
webrtc: Mac OS X Audio APIs will be utilized
webrtc: AttachAudioBuffer
webrtc:   OS info: OS X
webrtc:  Hardware model: MacBookAir6,2
webrtc:   number of availiable waveform-audio output devices is 3
webrtc:  Output device: Apple Inc. Built-in Output
webrtc: AudioMixerManagerMac::OpenSpeaker(id=38)
webrtc:  No process has hogged the input device
webrtc:   number of availiable waveform-audio input devices is 2
webrtc:  Input device: Apple Inc. Built-in Microphone
webrtc: AudioMixerManagerMac::OpenMicrophone(id=48)
webrtc:  No process has hogged the input device
webrtc: output: available=1
webrtc: output: available=1
webrtc: TransmitMixer::SetAudioProcessingModule(audioProcessingModule=0x1221bf0)
webrtc: OutputMixer::SetAudioProcessingModule(audioProcessingModule=0x1221bf0)
WebRtc VoiceEngine Version:
VoiceEngine 4.1.0
Applying audio options: AudioOptions {aec: true, agc: true, ns: true, hf: true, swap: false, typing: true, conference: false, agc_delta: 0, experimental_agc: false, experimental_aec: false, delay_agnostic_aec: false, experimental_ns: false, aec_dump: false, }
Error(webrtcvoiceengine.cc:1446): webrtc: Built-in AEC not supported on this platform
High pass filter enabled? 1
Stereo swapping enabled? 0
Typing detection is enabled? 1
Adjust agc delta is 0
Adjusting AGC level from default -2dB to -2dB
Aec dump is enabled? 0
Delay agnostic aec is enabled? 0
Experimental aec is enabled? 0
Experimental ns is enabled? 0
WebRtc VoiceEngine codecs:
opus/48000/2 (111)
ISAC/16000/1 (103)
ISAC/32000/1 (104)
G722/8000/1 (9)
ILBC/8000/1 (102)
PCMU/8000/1 (0)
PCMA/8000/1 (8)
CN/32000/1 (106)
CN/16000/1 (105)
CN/8000/1 (13)
red/8000/1 (127)
telephone-event/8000/1 (126)
WebRtcVoiceEngine::Init Done!
WebRtcVideoEngine2::Init
Applying audio options: AudioOptions {aec: true, agc: true, ns: true, hf: true, swap: false, typing: true, conference: false, agc_delta: 0, experimental_agc: false, experimental_aec: false, delay_agnostic_aec: false, experimental_ns: false, aec_dump: false, }
Error(webrtcvoiceengine.cc:1446): webrtc: Built-in AEC not supported on this platform
High pass filter enabled? 1
Stereo swapping enabled? 0
Typing detection is enabled? 1
Adjust agc delta is 0
Adjusting AGC level from default -2dB to -2dB
Aec dump is enabled? 0
Delay agnostic aec is enabled? 0
Experimental aec is enabled? 0
Experimental ns is enabled? 0
Setting microphone to (id=0, name=Default device) and speaker to (id=0, name=Default device)
Set microphone to (id=0 name=Default device) and speaker to (id=0 name=Default device)
Making key pair
Allowing SCTP data engine.
Returning key pair
Making certificate for WebRTC
Returning certificate
Making key pair
Local and Remote descriptions must be applied to get SSL Role of the session.
Error(webrtcsession.cc:1200): ConnectDataChannel called when data_channel_ is NULL.
Alice State: stable
Allowing SCTP data engine.
Returning key pair
Making certificate for WebRTC
Returning certificate
Making key pair
Bob State: stable
Returning key pair
Making certificate for WebRTC
Returning certificate
Returning key pair
Making certificate for WebRTC
Returning certificate
Session:8792605950890241566 Old state:STATE_INIT New state:STATE_RECEIVEDTERMINATE Type:urn:xmpp:jingle:apps:rtp:1 Transport:http://www.google.com/transport/p2p
Session:7365232863691173892 Old state:STATE_INIT New state:STATE_RECEIVEDTERMINATE Type:urn:xmpp:jingle:apps:rtp:1 Transport:http://www.google.com/transport/p2p
Total count of channels: 0
```

and there it stays just hanging...

the same also happens when I redirect any of the tests from node-webrtc to use webrtc native
such as https://github.com/js-platform/node-webrtc/blob/develop/test/connect.js but it seems consistent that it hangs after returning certificate.

**Comment by vmolsa** [comment]
Error(webrtcsession.cc:1200): ConnectDataChannel called when data_channel_ is NULL.
This error is causing from third_party/webrtc/src/talk/app/webrtc/webrtcsession.cc
WebRtcSession::ConnectDataChannel(DataChannel* webrtc_data_channel)

I don't know that if there is missing something or is it just bug on webrtc trunk. 
but this error is same on all platforms..?

**Comment by vmolsa** [comment]
It seems that there is missing something from the source. because every sctp datachannel test is passing

[----------] 24 tests from SctpDataChannelTest
[ RUN      ] SctpDataChannelTest.ConnectedToTransportOnCreated
[       OK ] SctpDataChannelTest.ConnectedToTransportOnCreated (0 ms)
[ RUN      ] SctpDataChannelTest.ConnectedAfterTransportBecomesAvailable
[       OK ] SctpDataChannelTest.ConnectedAfterTransportBecomesAvailable (0 ms)
[ RUN      ] SctpDataChannelTest.StateTransition
[       OK ] SctpDataChannelTest.StateTransition (0 ms)
[ RUN      ] SctpDataChannelTest.BufferedAmountWhenBlocked
[       OK ] SctpDataChannelTest.BufferedAmountWhenBlocked (0 ms)
[ RUN      ] SctpDataChannelTest.QueuedDataSentWhenUnblocked
[       OK ] SctpDataChannelTest.QueuedDataSentWhenUnblocked (0 ms)
[ RUN      ] SctpDataChannelTest.BlockedWhenSendQueuedDataNoCrash
[       OK ] SctpDataChannelTest.BlockedWhenSendQueuedDataNoCrash (0 ms)
[ RUN      ] SctpDataChannelTest.OpenMessageSent
[       OK ] SctpDataChannelTest.OpenMessageSent (0 ms)
[ RUN      ] SctpDataChannelTest.QueuedOpenMessageSent
[       OK ] SctpDataChannelTest.QueuedOpenMessageSent (0 ms)
[ RUN      ] SctpDataChannelTest.LateCreatedChannelTransitionToOpen
[       OK ] SctpDataChannelTest.LateCreatedChannelTransitionToOpen (2 ms)
[ RUN      ] SctpDataChannelTest.SendUnorderedAfterReceivesOpenAck
[       OK ] SctpDataChannelTest.SendUnorderedAfterReceivesOpenAck (2 ms)
[ RUN      ] SctpDataChannelTest.SendUnorderedAfterReceiveData
[       OK ] SctpDataChannelTest.SendUnorderedAfterReceiveData (1 ms)
[ RUN      ] SctpDataChannelTest.SendDataSsrc
[       OK ] SctpDataChannelTest.SendDataSsrc (0 ms)
[ RUN      ] SctpDataChannelTest.ReceiveDataWithInvalidSsrc
[       OK ] SctpDataChannelTest.ReceiveDataWithInvalidSsrc (0 ms)
[ RUN      ] SctpDataChannelTest.ReceiveDataWithValidSsrc
[       OK ] SctpDataChannelTest.ReceiveDataWithValidSsrc (0 ms)
[ RUN      ] SctpDataChannelTest.NoMsgSentIfNegotiatedAndNotFromOpenMsg
[       OK ] SctpDataChannelTest.NoMsgSentIfNegotiatedAndNotFromOpenMsg (2 ms)
[ RUN      ] SctpDataChannelTest.OpenAckSentIfCreatedFromOpenMessage
[       OK ] SctpDataChannelTest.OpenAckSentIfCreatedFromOpenMessage (1 ms)
[ RUN      ] SctpDataChannelTest.OpenAckRoleInitialization
[       OK ] SctpDataChannelTest.OpenAckRoleInitialization (0 ms)
[ RUN      ] SctpDataChannelTest.ClosedWhenSendBufferFull
[       OK ] SctpDataChannelTest.ClosedWhenSendBufferFull (15 ms)
[ RUN      ] SctpDataChannelTest.ClosedOnTransportError
[       OK ] SctpDataChannelTest.ClosedOnTransportError (0 ms)
[ RUN      ] SctpDataChannelTest.ClosedDataChannelDoesNotFireOnStateChange
[       OK ] SctpDataChannelTest.ClosedDataChannelDoesNotFireOnStateChange (0 ms)
[ RUN      ] SctpDataChannelTest.RemotePeerRequestClose
[       OK ] SctpDataChannelTest.RemotePeerRequestClose (0 ms)
[ RUN      ] SctpDataChannelTest.ClosedWhenReceivedBufferFull
[       OK ] SctpDataChannelTest.ClosedWhenReceivedBufferFull (10 ms)
[ RUN      ] SctpDataChannelTest.SendEmptyData
[       OK ] SctpDataChannelTest.SendEmptyData (0 ms)
[ RUN      ] SctpDataChannelTest.NeverOpened
[       OK ] SctpDataChannelTest.NeverOpened (0 ms)
[----------] 24 tests from SctpDataChannelTest (33 ms total)

**Comment by guymguym** [comment]
I see that there is still no change.
I sent PR https://github.com/vmolsa/webrtc-native/pull/5 with extensive tests which I also pushed to node-webrtc, and are still failing there too :(

**Comment by vmolsa** [comment]
Thanks, I created src/PeerConnectionTest.cc for testing webrtc library only. This is very strange issue because every gmock test is passing. But in webrtc-native CreateOffer request just hangs on background. (in webrtc thread). I don't know that is that really a bug on webrtc or just some kind of init function is missing from webrtrc-native. It's nice that webrtc trunk doesn't provide any good example for external projects...

**Comment by guymguym** [comment]
if you can select a stable webrtc revision (for example the one used in chrome 42) that would eliminate the possibility of a trunk issue...

**Comment by vmolsa** [comment]
:+1: 

https://chromium.googlesource.com/chromium/src/+/42.0.2311.153
https://chromium.googlesource.com/chromium/src/+/42.0.2311.153/DEPS
->

src/third_party/webrtc <- /external/webrtc/trunk/webrtc.git@8b9a856b98700ddb512da12a6e2b7b7dcb2d39ee

src/third_party/libjingle/source/talk <- 
/external/webrtc/trunk/talk.git@ff9171e7ac5309d1e5863c073315e29ddedbeb6a

**Comment by vmolsa** [comment]
Fixed.
