### ISSUE TITLE
Prebuilt binaries not found

### ISSUE THREAD

**Issue by NithyeshS** [vmolsa/webrtc-native#41]
When running `npm install webrtc-native --save`, I get the following:

>npm install webrtc-native --save
> webrtc-native@1.4.0 install /home/nithyesh/node_modules/webrtc-native
> node scripts/install.js
>
>Downloading module: webrtc-1.4.0-linux-x64-v6.9.x.node
>/home/nithyesh/node_modules/webrtc-native/scripts/install.js:78
>throw` new Error('prebuilt module not found. See the instructions from https://github.com/vmolsa/webrtc-native/wiki/Getting-started#building-from-source for building module from source.');
>      ^
>
>Error: prebuilt module not found. See the instructions from https://github.com/vmolsa/webrtc-native/wiki/Getting-started#building-from-source for building module from source.
>    at Request._callback (/home/nithyesh/node_modules/webrtc-native/scripts/install.js:78:13)
>    at Request.self.callback (/home/nithyesh/node_modules/request/request.js:186:22)
>    at emitTwo (events.js:106:13)
>    at Request.emit (events.js:191:7)
>    at Request.<anonymous> (/home/nithyesh/node_modules/request/request.js:1081:10)
>    at emitOne (events.js:101:20)
>    at Request.emit (events.js:188:7)
>    at IncomingMessage.<anonymous> (/home/nithyesh/node_modules/request/request.js:1001:12)
>    at IncomingMessage.g (events.js:291:16)
>    at emitNone (events.js:91:20)

It seems that the binaries are not present. Is there a way to proceed with this or is building from source my only option now?

**Comment by mogafk** [comment]
some problem
my os
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"
kernel 4.4.0-21-generic

**Comment by boldt** [comment]
The configured URL http://cide.cc:8080/webrtc/ in https://github.com/vmolsa/webrtc-native/blob/master/scripts/install.js#L10 is not available. Please fix it. Thanks.

**Comment by boldt** [comment]
@vmolsa Since your server is still down, I tried to build it on my own. But that fails for me. I do not get any `webrtc.node` after running `npm build`.  I really need the prebuilt binaries. Do you still have them somewhere? I you server continues to be down, I would host them. Just give me a response to handle this issue. Thx!

**Comment by vmolsa** [comment]
@boldt I'm making new bindings for webrtc-native version that uses github releases as a backend so requiring own server isn't needed anymore and i use the [libcrtc](https://github.com/vmolsa/libcrtc) because it is easier to compile on more than one platform.

The platforms supported by libcrtc can be seen [here](https://github.com/vmolsa/libcrtc/releases)

**Comment by boldt** [comment]
That sounds great! Any idea when libcrtc will be integrated into webrtc-native, so it's ready to use?

**Comment by vmolsa** [comment]
I hope that I have enough time to make changes at this week and get it published.

**Comment by boldt** [comment]
I'm looking forward to it. And to test it.

**Comment by vmolsa** [comment]
Finally, I got the first version released.

```sh
git clone https://github.com/vmolsa/webrtc-native
cd webrtc-native
git checkout v2.x
npm install
node test/mesh.js
```
But currently there are no other than osx supported. And I need to upgrade both libraries so I can get other platforms to work.

> Peers created: 20  ( expected: 20 )
Peers closed: 20  ( expected: 20 )
Datachannels opened: 200  ( expected: 200 )
Datachannels closed: 200  ( expected: 200 )
Messages received: 4000  ( expected: 4000 )
Messages sended: 4000  ( expected: 4000 )
Ping send count: 2000  ( expected: 2000 )
Ping received count: 2000  ( expected: 2000 )
Pong send count: 2000  ( expected: 2000 )
Pong received count: 2000  ( expected: 2000 )

**Comment by boldt** [comment]
Since I don't have an OSX, I cannot test it. I'm looking forward to the x86_64 build :-)

**Comment by boldt** [comment]
Any update on the  x86_64 build?

**Comment by boldt** [comment]
Do you have any time to work on the **x86_64** build? Can I help you somehow? My code is broken for over half a year now and would like to continue to work on it asap. Otherwise I have to search for a another node-based WebRTC API, which is hard to find...

**Comment by getkey** [comment]
See #43 ;-)

**Comment by boldt** [comment]
It's a pity. 

I found an old backup with a *x86_64* build, so I can continue with it.

**Comment by McPo** [comment]
Thanks @vmolsa for your branch, However I noticed the MediaStream APIs are missing on the v2.x branch, was this a deliberate action, or did you branch from another version pre-MediaStream?

**Comment by vmolsa** [comment]
Branch v2.x was too heavy (memory, cpu) for my purposes (chromium webrtc) and that's why i have dropped support for any chromium based solution.. for now i'm working with [ortc branch](https://github.com/vmolsa/webrtc-native/tree/ortc) and for your question about mediastream API i have decided to add support for streaming media from plain node stream and i'm not implementing any MediaStream/MediaStreamTrack.. But if you want still use chromium based solution then i suggest to use [node-webrtc](https://github.com/js-platform/node-webrtc) and open issue on that project.
